import { db } from '@/db'
import { downloads } from '@/db/schema'
import { InferInsertModel } from 'drizzle-orm'

const mockDownloads: InferInsertModel<typeof downloads>[] = [
	{
		id: 'mock-1',
		title: 'United in Grief',
		artist: 'Kendrick Lamar',
		album: 'Family Matters',
		trackCount: 1,
		tracksCompleted: 0,
		totalBytes: 4_857_600,
		downloadedBytes: 428_800,
		sourceUrl: 'magnet:?xt=urn:btih:mock1',
		type: 'torrent',
		status: 'downloading',
		createdAt: Date.now(),
		updatedAt: Date.now(),
	},
	{
		id: 'mock-2',
		title: 'Live at the Jazz Club',
		artist: 'The Blue Notes',
		album: 'Live at the Jazz Club',
		trackCount: 8,
		tracksCompleted: 0,
		totalBytes: 62914560,
		downloadedBytes: 0,
		sourceUrl: 'magnet:?xt=urn:btih:mock2',
		type: 'torrent',
		status: 'pending',
		createdAt: Date.now() - 1000,
		updatedAt: Date.now() - 1000,
	},
	{
		id: 'mock-3',
		title: 'Greatest Hits Remastered',
		artist: 'Sofia Reyes',
		album: 'Greatest Hits Remastered',
		trackCount: 16,
		tracksCompleted: 16,
		totalBytes: 136314880,
		downloadedBytes: 136314880,
		sourceUrl: 'https://example.com/greatest-hits.zip',
		type: 'http',
		status: 'done',
		createdAt: Date.now() - 2000,
		updatedAt: Date.now() - 2000,
	},
	{
		id: 'mock-4',
		title: 'Corrupted Album',
		artist: 'Vektroid',
		album: 'Corrupted Album',
		trackCount: 10,
		tracksCompleted: 0,
		totalBytes: 83886080,
		downloadedBytes: 12582912,
		sourceUrl: 'magnet:?xt=urn:btih:mock4',
		type: 'torrent',
		status: 'error',
		errorMsg: 'Connection timed out',
		createdAt: Date.now() - 3000,
		updatedAt: Date.now() - 3000,
	},
	{
		id: 'mock-5',
		title: 'Indie Rock Collection',
		artist: 'Various Artists',
		album: 'Indie Rock Collection',
		trackCount: 20,
		tracksCompleted: 20,
		totalBytes: 178257920,
		downloadedBytes: 178257920,
		sourceUrl: 'https://example.com/indie-rock.zip',
		type: 'http',
		status: 'done',
		createdAt: Date.now() - 4000,
		updatedAt: Date.now() - 4000,
	},
	{
		id: 'mock-6',
		title: 'Bootleg Sessions 1998',
		artist: 'Marlo',
		album: 'Bootleg Sessions 1998',
		trackCount: 9,
		tracksCompleted: 6,
		totalBytes: 94371840,
		downloadedBytes: 68889395,
		sourceUrl: 'magnet:?xt=urn:btih:mock6',
		type: 'torrent',
		status: 'downloading',
		createdAt: Date.now() - 5000,
		updatedAt: Date.now() - 5000,
	},
	{
		id: 'mock-7',
		title: 'Ambient Textures EP',
		artist: 'Lost Frequencies',
		album: 'Ambient Textures EP',
		trackCount: 6,
		tracksCompleted: 5,
		totalBytes: 47185920,
		downloadedBytes: 41523609,
		sourceUrl: 'https://example.com/ambient-textures.zip',
		type: 'http',
		status: 'downloading',
		createdAt: Date.now() - 6000,
		updatedAt: Date.now() - 6000,
	},
	{
		id: 'mock-8',
		title: 'Unreleased Demos Vol.2',
		artist: 'Kx5',
		album: 'Unreleased Demos Vol.2',
		trackCount: 7,
		tracksCompleted: 0,
		totalBytes: 58720256,
		downloadedBytes: 0,
		sourceUrl: 'magnet:?xt=urn:btih:mock8',
		type: 'torrent',
		status: 'pending',
		createdAt: Date.now() - 7000,
		updatedAt: Date.now() - 7000,
	},
	{
		id: 'mock-9',
		title: 'Soundtrack Compilation',
		artist: 'Various Artists',
		album: 'Soundtrack Compilation',
		trackCount: 24,
		tracksCompleted: 1,
		totalBytes: 209715200,
		downloadedBytes: 10485760,
		sourceUrl: 'https://example.com/soundtrack-compilation.zip',
		type: 'http',
		status: 'error',
		errorMsg: '404 Not Found',
		createdAt: Date.now() - 8000,
		updatedAt: Date.now() - 8000,
	},
	{
		id: 'mock-10',
		title: 'Acoustic Sessions',
		artist: 'Neon Waves',
		album: 'Acoustic Sessions',
		trackCount: 11,
		tracksCompleted: 11,
		totalBytes: 89128960,
		downloadedBytes: 89128960,
		sourceUrl: 'magnet:?xt=urn:btih:mock10',
		type: 'torrent',
		status: 'done',
		createdAt: Date.now() - 9000,
		updatedAt: Date.now() - 9000,
	},
	{
		id: 'mock-11',
		title: 'Vinyl Rips 1970-1980',
		artist: 'Various Artists',
		album: 'Vinyl Rips 1970-1980',
		trackCount: 18,
		tracksCompleted: 5,
		totalBytes: 157286400,
		downloadedBytes: 45613056,
		sourceUrl: 'magnet:?xt=urn:btih:mock11',
		type: 'torrent',
		status: 'paused',
		createdAt: Date.now() - 10000,
		updatedAt: Date.now() - 10000,
	},
	{
		id: 'mock-12',
		title: 'Electronic Mixtape',
		artist: 'Golden Hour',
		album: 'Electronic Mixtape',
		trackCount: 14,
		tracksCompleted: 2,
		totalBytes: 125829120,
		downloadedBytes: 75497472,
		sourceUrl: 'https://example.com/electronic-mixtape.zip',
		type: 'http',
		status: 'error',
		errorMsg: 'Connection reset by peer',
		createdAt: Date.now() - 11000,
		updatedAt: Date.now() - 11000,
	},
	{
		id: 'mock-13',
		title: 'Podcast Archive 2023',
		artist: 'Analog Dreams',
		album: 'Podcast Archive 2023',
		trackCount: 30,
		tracksCompleted: 0,
		totalBytes: 251658240,
		downloadedBytes: 0,
		sourceUrl: 'https://example.com/podcast-archive.zip',
		type: 'http',
		status: 'pending',
		createdAt: Date.now() - 12000,
		updatedAt: Date.now() - 12000,
	},
	{
		id: 'mock-14',
		title: 'Rare B-Sides Collection',
		artist: 'Echoes in the Dark',
		album: 'Rare B-Sides Collection',
		trackCount: 13,
		tracksCompleted: 13,
		totalBytes: 109051904,
		downloadedBytes: 109051904,
		sourceUrl: 'magnet:?xt=urn:btih:mock14',
		type: 'torrent',
		status: 'done',
		createdAt: Date.now() - 13000,
		updatedAt: Date.now() - 13000,
	},
]

export const seedMockDownloads = async () => {
	await db.delete(downloads)
	await db.insert(downloads).values(mockDownloads)
}
