import { db } from '@/db'
import { downloads } from '@/db/schema'

const mockDownloads = [
	{
		id: 'mock-1',
		title: 'Discography Pack Vol.1',
		sourceUrl: 'magnet:?xt=urn:btih:mock1',
		type: 'torrent',
		status: 'downloading',
		progress: 0.42,
		createdAt: Date.now(),
	},
	{
		id: 'mock-2',
		title: 'Live at the Jazz Club',
		sourceUrl: 'magnet:?xt=urn:btih:mock2',
		type: 'torrent',
		status: 'pending',
		progress: 0,
		createdAt: Date.now() - 1000,
	},
	{
		id: 'mock-3',
		title: 'Greatest Hits Remastered',
		sourceUrl: 'https://example.com/greatest-hits.zip',
		type: 'http',
		status: 'done',
		progress: 1,
		createdAt: Date.now() - 2000,
	},
	{
		id: 'mock-4',
		title: 'Corrupted Album',
		sourceUrl: 'magnet:?xt=urn:btih:mock4',
		type: 'torrent',
		status: 'error',
		progress: 0.15,
		errorMsg: 'Connection timed out',
		createdAt: Date.now() - 3000,
	},
	{
		id: 'mock-5',
		title: 'Indie Rock Collection',
		sourceUrl: 'https://example.com/indie-rock.zip',
		type: 'http',
		status: 'done',
		progress: 1,
		createdAt: Date.now() - 4000,
	},
	{
		id: 'mock-6',
		title: 'Bootleg Sessions 1998',
		sourceUrl: 'magnet:?xt=urn:btih:mock6',
		type: 'torrent',
		status: 'downloading',
		progress: 0.73,
		createdAt: Date.now() - 5000,
	},
	{
		id: 'mock-7',
		title: 'Ambient Textures EP',
		sourceUrl: 'https://example.com/ambient-textures.zip',
		type: 'http',
		status: 'downloading',
		progress: 0.88,
		createdAt: Date.now() - 6000,
	},
	{
		id: 'mock-8',
		title: 'Unreleased Demos Vol.2',
		sourceUrl: 'magnet:?xt=urn:btih:mock8',
		type: 'torrent',
		status: 'pending',
		progress: 0,
		createdAt: Date.now() - 7000,
	},
	{
		id: 'mock-9',
		title: 'Soundtrack Compilation',
		sourceUrl: 'https://example.com/soundtrack-compilation.zip',
		type: 'http',
		status: 'error',
		progress: 0.05,
		errorMsg: '404 Not Found',
		createdAt: Date.now() - 8000,
	},
	{
		id: 'mock-10',
		title: 'Acoustic Sessions',
		sourceUrl: 'magnet:?xt=urn:btih:mock10',
		type: 'torrent',
		status: 'done',
		progress: 1,
		createdAt: Date.now() - 9000,
	},
	{
		id: 'mock-11',
		title: 'Vinyl Rips 1970-1980',
		sourceUrl: 'magnet:?xt=urn:btih:mock11',
		type: 'torrent',
		status: 'downloading',
		progress: 0.29,
		createdAt: Date.now() - 10000,
	},
	{
		id: 'mock-12',
		title: 'Electronic Mixtape',
		sourceUrl: 'https://example.com/electronic-mixtape.zip',
		type: 'http',
		status: 'error',
		progress: 0.6,
		errorMsg: 'Connection reset by peer',
		createdAt: Date.now() - 11000,
	},
	{
		id: 'mock-13',
		title: 'Podcast Archive 2023',
		sourceUrl: 'https://example.com/podcast-archive.zip',
		type: 'http',
		status: 'pending',
		progress: 0,
		createdAt: Date.now() - 12000,
	},
	{
		id: 'mock-14',
		title: 'Rare B-Sides Collection',
		sourceUrl: 'magnet:?xt=urn:btih:mock14',
		type: 'torrent',
		status: 'done',
		progress: 1,
		createdAt: Date.now() - 13000,
	},
]

export const seedMockDownloads = async () => {
	await db.delete(downloads)
	await db.insert(downloads).values(mockDownloads)
}
